name: golang

on:
  push:
    paths:
    - .github/workflows/go.yaml
    - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Setup gotestsum
      uses: autero1/action-gotestsum@v0.1.0
      with:
        gotestsum_version: 1.6.1
    - name: run go test
      run: | 
        cd go
        gotestsum --format dots