name: golang

on:
  push:
    paths:
    - .github/workflows/golang.yaml
    - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: run go test
      run: go test ./go/...